### ISSUE TITLE
Maybe unsound in SpecializeArgs::env

### ISSUE THREAD

**Issue by lwz23** [Mufanc/z-loader#6]
hello, thank you for your contribution in this project, I am scanning the unsoundness problem in rust project.
I notice the following code:
```
pub struct SpecializeArgs {
    ptr: *const u64,
    pub env: *mut JNIEnv,
.......................
pub is_system_server: *mut bool,
.........................
}

impl SpecializeArgs{
..............................
    pub fn env(&self) -> JNIEnv {
        unsafe { *self.env }
    }

    pub fn is_system_server(&self) -> bool {
        unsafe { *self.is_system_server }
    }
}
```
Considering that `pub mod zygote`, `env` and `is_system_server` are `pub` field, and `env` `is_system_server` are also pub function. I assume that users can directly manipulate this field. This potential situation could result in `*self.is_system_server` being dereference a null pointer, and directly dereferencing it might trigger undefined behavior (UB). For safety reasons, I felt it necessary to report this issue. If you have performed checks elsewhere that ensure this is safe, please don’t take offense at my raising this issue.
If there is no external usage for `SpecializeArgs`, I suggest it should not marked as `pub`, at least its field should not marked as `pub`.

**Comment by lwz23** [comment]
maybe also result in UB in
https://github.com/Mufanc/z-loader/blob/ff8cf7015b67a23a021c6a8541bb84b48408795f/common/src/zygote.rs#L92
if `ptr` is null_pointer

**Comment by Mufanc** [comment]
Thank you for your correction! I will pay attention to this in future coding. :smile:
